image: python:3.9

before_script:
  - pip install mkdocs
  - pip install mkdocs-material
  - pip install mkdocstrings[python]

pages:
  script:
    - mkdocs build -d public
  artifacts:
    paths:
      - public
  only:
    - main
