# Generated by Django 5.0.3 on 2024-03-26 17:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=150, unique=True)),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='subcategories', related_query_name='subcategory', to='course_management.category')),
            ],
        ),
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50)),
                ('min_age', models.PositiveSmallIntegerField()),
                ('max_age', models.PositiveSmallIntegerField()),
                ('image', models.ImageField(blank=True, null=True, upload_to='course_images/')),
                ('status', models.CharField(choices=[('active', 'Active'), ('hidden', 'Hidden'), ('archived', 'Archived')], default='hidden', max_length=25)),
                ('note', models.TextField(blank=True, null=True)),
                ('categories', models.ManyToManyField(related_name='courses', related_query_name='course', to='course_management.category')),
            ],
        ),
        migrations.CreateModel(
            name='File',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('lesson_number', models.PositiveSmallIntegerField(blank=True, default=0)),
                ('name', models.CharField(max_length=100, unique=True)),
                ('path', models.FileField(upload_to='course_files/')),
                ('type', models.CharField(choices=[('presentation', 'Presentation'), ('project', 'Project'), ('draft', 'Draft'), ('homework', 'Homework'), ('other', 'Other')], default='other', max_length=50)),
                ('description', models.TextField(blank=True, null=True)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='files', to='course_management.course')),
            ],
        ),
    ]
