# Generated by Django 5.0.3 on 2024-05-01 11:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course_management', '0002_alter_file_course'),
    ]

    operations = [
        migrations.CreateModel(
            name='Lesson',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('lesson_number', models.PositiveSmallIntegerField(blank=True, default=0)),
                ('name', models.CharField(max_length=100)),
                ('presentation', models.FileField(blank=True, null=True, upload_to='course_files/')),
                ('presentationURL', models.URLField(blank=True, null=True)),
                ('additional_file', models.FileField(blank=True, null=True, upload_to='course_files/')),
                ('description', models.TextField(blank=True, null=True)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lessons', related_query_name='lesson', to='course_management.course')),
            ],
        ),
        migrations.DeleteModel(
            name='File',
        ),
    ]
