# Generated by Django 5.0.3 on 2024-05-02 11:39

import course_management.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course_management', '0003_lesson_delete_file'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lesson',
            name='additional_file',
            field=models.FileField(blank=True, null=True, upload_to=course_management.models.presentation_upload_path),
        ),
        migrations.AlterField(
            model_name='lesson',
            name='presentation',
            field=models.FileField(blank=True, null=True, upload_to=course_management.models.presentation_upload_path),
        ),
    ]
