# Generated by Django 5.0.3 on 2024-06-18 12:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course_management', '0004_alter_lesson_additional_file_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='link',
            field=models.URLField(blank=True, null=True),
        ),
    ]
