# Generated by Django 5.0.3 on 2024-03-26 17:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('partner_management', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='bank_account_number',
            field=models.IntegerField(),
        ),
    ]
