# Generated by Django 5.0.3 on 2024-04-02 18:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('partner_management', '0003_alter_employee_bank_account_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='partner',
            name='address_note',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='partner',
            name='house',
            field=models.PositiveSmallIntegerField(null=True),
        ),
        migrations.AddField(
            model_name='partner',
            name='street',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='partner',
            name='city',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='partner',
            name='country',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='partner',
            name='region',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
