# Generated by Django 5.0.3 on 2024-04-02 18:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('partner_management', '0004_partner_address_note_partner_house_partner_street_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='partner',
            name='city',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='partner',
            name='country',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='partner',
            name='house',
            field=models.PositiveSmallIntegerField(),
        ),
        migrations.AlterField(
            model_name='partner',
            name='region',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='partner',
            name='street',
            field=models.CharField(max_length=50),
        ),
    ]
