# Generated by Django 5.0.3 on 2024-04-08 19:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('partner_management', '0005_alter_partner_city_alter_partner_country_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='branch',
            name='partner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='branches', related_query_name='branch', to='partner_management.partner'),
        ),
    ]
