# Generated by Django 5.0.3 on 2024-04-13 17:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('partner_management', '0006_alter_branch_partner'),
    ]

    operations = [
        migrations.AddField(
            model_name='branch',
            name='area',
            field=models.PositiveSmallIntegerField(null=True),
        ),
        migrations.AddField(
            model_name='branch',
            name='floor',
            field=models.PositiveSmallIntegerField(null=True),
        ),
    ]
