# Generated by Django 5.0.3 on 2024-04-13 17:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('partner_management', '0007_branch_area_branch_floor'),
    ]

    operations = [
        migrations.AlterField(
            model_name='branch',
            name='floor',
            field=models.PositiveSmallIntegerField(),
        ),
    ]
