# Generated by Django 5.0.3 on 2024-05-05 17:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course_management', '0004_alter_lesson_additional_file_and_more'),
        ('partner_management', '0008_alter_branch_floor'),
    ]

    operations = [
        migrations.AlterField(
            model_name='partner',
            name='courses',
            field=models.ManyToManyField(related_name='partners_with_access', related_query_name='partners_with_access', to='course_management.course'),
        ),
    ]
