# Generated by Django 5.0.3 on 2024-05-02 11:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_management', '0003_alter_user_managers'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='gender',
            field=models.CharField(choices=[('man', 'man'), ('woman', 'woman'), ('undefined', 'undefined')], default='undefined', max_length=25),
        ),
    ]
