# Generated by Django 5.0.3 on 2024-05-13 14:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user_management', '0004_alter_user_gender'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='note',
        ),
    ]
